Repository nozzlegear/ShopifySharp, pull requests merged in 2024-01, with the labels that each got.

#990 Make CartUpdatedPayload.Note nullable
  ShopifySharp.Tests/ShopifySharp.Tests.csproj
  ShopifySharp.Tests/WebhookPayloads/CartUpdatedPayloadTests.cs
  ShopifySharp.Tests/WebhookPayloads/cart_updated_payload_with_null_note.json
  ShopifySharp/WebhookPayloads/CartUpdated/CartUpdatedPayload.cs
Labels: missing or invalid properties

#997 Fix X-ShopId header check when header value is empty
  ShopifySharp/Utilities/ShopifyDomainUtility.cs
Labels: bug

#994 Update readme.md
  readme.md
Labels: documentation
